listen: "0.0.0.0:8080"
primary: "https://primary.example.com"
backup: "https://backup-bucket.s3.amazonaws.com"
check_interval: "2s"
fail_threshold: 3
recover_threshold: 2
max_body: "10MB"
json_logs: false

# Auto Incident Reports (optional)
# webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
# webhook_format: "slack"  # Options: "slack" or "discord"
