[build]
builder = "NIXPACKS"
buildCommand = "cargo build --release"

[deploy]
startCommand = "cargo run --release -- --primary=$PRIMARY_URL --backup=$BACKUP_URL --listen=0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "failover"

